export const list = [
    {
        "id":1,
        "title": "Korean-Duffel-Bag",
        "type": "dairy",
        "description": "Korean-Duffel-Bag in cart",
        "filename": "https://shop.hallyusg.net/wp-content/uploads/2019/05/mademoiselle-aurore-duffle-bag-3.jpg",
        "price": 100,
        "quantity": 0,
    },
    {
        "id":2,
        "title": "Korean-Travel-Multi-Pouch",
        "type": "dairy",
        "description": "Korean-Travel-Multi-Pouch in cart",
        "filename": "https://shop.hallyusg.net/wp-content/uploads/2019/05/pouch-camper-rabbit-travel-multi-v3L-2-600x450.jpg",
        "price": 200,
        "quantity": 0,
    },
    {
        "id":3,
        "title": "Korean-Travel-Flower-Bag",
        "type": "dairy",
        "description": "Korean-Flower-Bag in cart",
        "filename": "https://shop.hallyusg.net/wp-content/uploads/2019/05/bag-jumping-rope-duffle-4.jpg",
        "price": 300,
        "quantity": 0,
    },
    {
        "id":4,
        "title": "Ethnic-Shoulder-Bag",
        "type": "dairy",
        "description": "Ethnic-Shoulder-Bag in cart",
        "filename": "https://shop.hallyusg.net/wp-content/uploads/2019/05/bag-ethnic-shoulder-water-fog-4-600x450.jpg",
        "price": 400,
        "quantity": 0,
    },
    {
        "id":5,
        "title": "Korean-Dinner-Plates",
        "type": "dairy",
        "description": "Korean-Dinner-Plates in cart",
        "filename": "https://shop.hallyusg.net/wp-content/uploads/2019/05/walk-together-02-e1554187206863-600x450.jpg",
        "price": 500,
        "quantity": 0,
    },
    {
        "id":6,
        "title": "Korean-Dinner-Fruit",
        "type": "dairy",
        "description": "Korean-Dinner-Fruit in cart",
        "filename": "https://shop.hallyusg.net/wp-content/uploads/2019/05/fruits-03-e1554186334125-600x450.jpg",
        "price": 600,
        "quantity": 0,
    },
    {
        "id":7,
        "title": "Korean-Dinner-Flower",
        "type": "dairy",
        "description": "Korean-Dinner-Flower in cart",
        "filename": "https://shop.hallyusg.net/wp-content/uploads/2019/05/plate-flower-aurore-2-600x450.jpg",
        "price": 700,
        "quantity": 0,
    },
    {
        "id":8,
        "title": "Korean-Dinner-Angel",
        "type": "dairy",
        "description": "Korean-Dinner-Angel in cart",
        "filename": "https://shop.hallyusg.net/wp-content/uploads/2019/05/plate-garden-of-angel-2-600x450.jpg",
        "price": 800,
        "quantity": 0,
    }
  ];